// core
export { createIcon } from "./createIcon";
export { path, strokePath } from "./paths";

// icons
export {
  EditIcon,
  NotificationIcon,
  UserIcon,
  AddImage,
  Bin,
  List,
  Logout,
  NotificationFilledIcon,
  MailIcon,
  MenuIcon,
  Pencil,
  CheckedCard,
  Phone,
  DetailIcon,
  TagIcon,
  CheckedCircle,
  History,
  QrIcon,
  ExclamationCircleIcon,
  SpinnerIcon,
  QuarterSpinnerIcon,
  Card,
  ChevronDownIcon,
  CalendarIcon,
  ClockIcon,
  CloseIcon,
  WrenchIcon,
  SearchIcon,
  categoryIcon,
  serviceIcon,
  promotionCodeIcon,
  MapIcon,
  PlusIcon,
} from "./icons";
